description = "GraphQL plugin for Ktor servers"

val jacocoSyntheticClassExcludes = listOf(
    // Kotlin emits DefaultImpls bridge classes for interface default methods. These classes are
    // compiler-generated bytecode artifacts and are reported by JaCoCo even though they are not
    // meaningful source-level code to test directly.
    "**/com/expediagroup/graphql/server/ktor/subscriptions/*\$DefaultImpls.class",
    // Ktor route and status-page lambdas compiled from Kotlin create anonymous handler classes with
    // names like GraphQLRoutesKt$graphQLPostRoute$route$1. These are generated implementation details
    // of the routing DSL, not named application classes, and they started affecting coverage after
    // the dependency upgrades.
    "**/com/expediagroup/graphql/server/ktor/GraphQLRoutesKt\$*.class",
    "**/com/expediagroup/graphql/server/ktor/GraphQLStatusPagesKt\$*.class"
)

plugins {
    id("com.expediagroup.graphql.conventions")
}

dependencies {
    api(projects.graphqlKotlinServer)
    api(projects.graphqlKotlinFederation)
    api(libs.ktor.serialization.jackson)
    api(libs.ktor.server.core)
    api(libs.ktor.server.content)
    api(libs.ktor.server.websockets)
    api(libs.ktor.server.statuspages)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.ktor.client.content)
    testImplementation(libs.ktor.client.websockets)
    testImplementation(libs.ktor.server.cio)
    testImplementation(libs.ktor.server.test.host)
    constraints {
        implementation(libs.commons.codec) {
            because("Cxeb68d52e-5509: Apache commons-codec before 1.13 is vulnerable to information exposure. https://devhub.checkmarx.com/cve-details/Cxeb68d52e-5509/")
        }
    }
}

tasks {
    jacocoTestReport {
        classDirectories.setFrom(
            sourceSets.main.get().output.asFileTree.matching {
                exclude(jacocoSyntheticClassExcludes)
            }
        )
    }
    jacocoTestCoverageVerification {
        classDirectories.setFrom(
            sourceSets.main.get().output.asFileTree.matching {
                exclude(jacocoSyntheticClassExcludes)
            }
        )
        violationRules {
            rule {
                limit {
                    counter = "INSTRUCTION"
                    value = "COVEREDRATIO"
                    minimum = "0.67".toBigDecimal()
                }
                limit {
                    counter = "BRANCH"
                    value = "COVEREDRATIO"
                    minimum = "0.48".toBigDecimal()
                }
            }
        }
    }
}
