name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
categories:
  - title: Major Changes
    label: "changes: major"

  - title: Minor Changes
    label: "changes: minor"

  - title: Patch Changes
    label: "changes: patch"
    
  - title: Other Changes

template: |
  $CHANGES
