#
# codecov.io Configuration
# See the docs here: https://docs.codecov.io/docs/codecov-yaml
#

# Ingore the example apps and docs from coverage reports
ignore:
  - "examples/**"
  - "website/**"
  - "docs/**"
