description = "Spring Boot autoconfiguration library for creating reactive GraphQL server"

val jacocoSyntheticClassExcludes = listOf(
    // Kotlin emits DefaultImpls bridge classes for interface default methods. These classes are
    // compiler-generated bytecode artifacts and are reported by JaCoCo even though they are not
    // meaningful source-level code to test directly.
    "**/com/expediagroup/graphql/server/spring/subscriptions/*\$DefaultImpls.class",
    // Spring functional routes compiled from Kotlin create anonymous handler classes with names like
    // *RouteConfiguration$...$1$1. These are generated implementation details of the route DSL, not
    // named application classes, and they started affecting branch coverage after the Spring upgrade.
    "**/com/expediagroup/graphql/server/spring/*RouteConfiguration\$*\$1\$1.class",
    "**/com/expediagroup/graphql/server/spring/*RoutesConfiguration\$*\$1\$1.class",
    // Kotlin also generates a coroutine state-machine class for this suspend handler method.
    "**/SubscriptionWebSocketHandler\$handle\$1.class"
)

plugins {
    id("com.expediagroup.graphql.conventions")
    alias(libs.plugins.kotlin.spring)
    id(libs.plugins.kotlin.kapt.get().pluginId)
}

dependencies {
    api(projects.graphqlKotlinServer)
    api(projects.graphqlKotlinFederation)
    api(libs.spring.boot.webflux.module)
    api(libs.spring.boot.autoconfigure)
    api(libs.spring.boot.netty)
    api(libs.spring.boot.jackson)
    api(libs.kotlinx.coroutines.jdk8)
    api(libs.kotlinx.coroutines.reactor)
    api(libs.reactor.extensions)
    api(libs.fastjson2.spring)
    kapt(libs.spring.boot.config)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.spring.boot.test)
    testImplementation(libs.spring.boot.webtestclient)
    testImplementation(libs.reactor.test)
}

tasks {
    jacocoTestReport {
        classDirectories.setFrom(
            sourceSets.main.get().output.asFileTree.matching {
                exclude(jacocoSyntheticClassExcludes)
            }
        )
    }
    jacocoTestCoverageVerification {
        classDirectories.setFrom(
            sourceSets.main.get().output.asFileTree.matching {
                exclude(jacocoSyntheticClassExcludes)
            }
        )
        violationRules {
            rule {
                limit {
                    counter = "INSTRUCTION"
                    value = "COVEREDRATIO"
                    minimum = "0.82".toBigDecimal()
                }
                limit {
                    counter = "BRANCH"
                    value = "COVEREDRATIO"
                    minimum = "0.67".toBigDecimal()
                }
            }
        }
    }
    named("dokkaGeneratePublicationHtml") {
        dependsOn("kaptKotlin")
    }
}
