graphql:
  packages:
    - "com.expediagroup.graphql.examples.server.spring"
  playground:
    enabled: true
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000
    protocol: "APOLLO_SUBSCRIPTIONS_WS"
